#!/bin/bash
commit_sha=`git rev-parse --verify HEAD`
if [ -z "$commit_sha" ]; then
    echo "SCEALAI ERROR: COMMIT SHA EMTPY: QUITTING"
    exit
fi

if [ ! -f ./devops/publish_qa_static.sh ]; then
    echo "SCEALAI ERROR: REQUIRE DIRECTORY IN cwd: ./devops/publish_qa_static.sh"
    exit
fi

cmd="cd /home/scealai/qa/An-Scealai && \
    git stash && \
    git fetch && \
    git checkout $commit_sha && \
    git submodule update --recursive && \
    npm i --prefix api && \
    sudo /bin/systemctl restart scealai-qa && \
    sleep 3 && \
    journalctl -u scealai-qa"
ssh -v -t scealai@banba "$cmd"
bash ./devops/publish_qa_static.sh