from ubuntu
run apt update; apt upgrade -y
run apt install -y liblingua-ga-gramadoir-perl
run apt install -y libcgi-pm-perl
run apt install -y libdatetime-perl
run apt install -y libjson-perl
run apt install -y libencode-perl
run apt install -y liblog-dispatch-filerotate-perl
run apt install -y libapache2-mod-fcgid
copy gramadoir /usr/bin/gramadoir
run chmod +x /usr/bin/gramadoir