export default [
    'Ní raibh líon mór daoine bainteach leis an scaifte a bhí ag iarraidh mioscais a chothú.',
    'Ach thosnaíos-sa ag léamh agus bhog mé isteach ionam féin.',
    'Tabhair go leor leor de na na rudaí do do chara, a Chaoimhín.',
    'Seo é a chuntas féin ar ar tharla ina dhiaidh sin.',
    'Aithníonn ciaróg ciaróg eile.',
    'Go deo deo arís ní fheicfeadh sí a cheannaithe snoite.',
    'Tabhair iad seo do do mháthair.',
    'Sin é é ...  Tá sé anseo!',
    'Tá siad le feiceáil ann le fada fada an lá.',
    'Bhí go leor leor le rá aici.',
    'Cuirfidh mé mé féin in aithne dá lán ciníocha.',
    'Fanann réalta chobhsaí ar feadh idir milliún agus milliún milliún bliain.',
    'Bhíodh an-tóir ar spíosraí go mór mór.',
    'Bhí an dara cupán tae ólta agam nuair a tháinig an fear mór mór.',
    'Agus sin sin de sin!',
    'Chuaigh sí in olcas ina dhiaidh sin agus bhí an-scanradh orthu.',
    'Tharla sé seo ar lá an-mífheiliúnach, an Déardaoin.',
    'Ní maith liom na daoine míintleachtúla.',
    'Trí chomhtharlúint, bhí siad sa tuaisceart ag an am.',
    'Sílim nárbh ea, agus is docha nach bhfuil i gceist ach easpa smaoinimh.',
    'Tá súil le feabhas nuair a thosóidh airgead ag teacht isteach ó ola agus gás i mBearna Timor.',
    'Bhí sí cosúil le claíomh Damocles ar crochadh sa spéir.',
    'Beidh nuachtáin shuaracha i ngreim cé nach mbeadh cinsireacht den droch-chinéal i gceist.',
    'Bhí sé páirteach sa chéad léiriú poiblí de Adaptation.',
    'Beidh an tionchar le mothú níos mó i gcás comhlachtaí Éireannacha mar gur mionairgeadra é an punt.',
    'Bhí an dream dí-armtha ag iarraidh a gcuid gunnaí.',
    'An bhfuil uachtar roeite agattt?',
    'Bíonn an geál ag satailt ar an dubh.',
    'Ach go rithe an fhíréantacht mar uisce agus an t-ionracas mar shruth gan dísc!',
    'Ba iad mo shinsear rithe Chúige Uladh.',
    'Is iad na trí cholún sin le cheile an tAontas Eorpach.',
    'Scriúáil sé an glas seo ar chúl an doras.',
    'Ach bhí mé ag leanúint ar aghaidh an t-am ar fad leis.',
    'Bhain sé sult as clár toghcháin TG4 a chur i láthair an mhí seo caite.',
    'Bhrostaigh sé go dtí an t-ospidéal.',
    'Sa dara alt, déan cur síos ar a bhfaca siad sa Spáinn.',
    'D\'oirfeadh síol áitiúil níos fearr ná an síol a hadhlaic sé anuraidh.',
    'Ná hinis do dhuine ar bith é.',
    'Tá ceacht stairiúil uathúil do chuairteoirí san t-ionad seo.',
    'Faightear an t-ainm isteach faoin tír freisin.',
    'Cén t-ainm atá air?',
    'Aistríodh é go tSualainnis, Gearmáinis, agus Fraincis.',
    'Cén chaoi a n-aimsíonn scoil an tseirbhís seo?',
    'Tá sonraí ann faoin tslí ina n-iarrtar taifid faoin Acht.',
    'Cén tslí bheatha a bhí ag Naoi?',
    'Bhí imní ag teacht ar dheartháir an tsagairt.',
    'Tá sé riachtanach ar mhaithe le feidhmiú an phlean a bheidh ceaptha ag an eagraíocht ceannasach.',
    'Bhí na ranganna seo ar siúl an bhliain seo caite.',
    'Léimeann an fharraige céad méadar suas sa spéir.',
    'Briseadh bád Éamoinn Óig oíche gaoithe móire.',
    'Bhíodh na daoir scaoilte saor óna gcuid oibre agus bhíodh saoirse cainte acu.',
    'Bhí mé ag tógáil balla agus ag baint móna.',
    'Is as Londain Shasana mé ó dhúchas.',
    'Seán a d\'imigh ar iarraidh ar oíche ghaoithe móire.',
    'Mar chuid den socrú beidh Michelle ag labhairt Ghaeilge ag ócáidí poiblí.',
    'Tugadh cuireadh dó a theacht i láthair an fhir móir.',
    'Tugaimid é amach le haghaidh béile Polainéisigh. ',
    'Bhí torann an dorais cloiste agam.',
    'Tá na lachain slachtmhara ar eitilt.',
    'Mhair cuid mhór dár sinsir céad caoga bliain ó shin.',
    'Tá sé le cloisteáil sna meáin gach seachtain.',
    'Déanann siad na breiseáin brabhsála don tionscal ríomhaireachta.',
    'Is ar éisc mara agus ar na hainmhithe mara eile atáimid ag díriú.',
    'Chonaic mé líon agus crainn tógála ann.',
    'Bhí pictiúir le feiceáil ar scáileáin theilifíse ar fud an domhain.',
    'Maidin lá ar na mhárach thug a fhear gaoil cuairt air.',
    'Cad é mar a tá tú?',
    'Bhí deich tobar fíoruisce agus seachtó crann pailme ann.',
    'Rinneadh an roinnt do na naoi treibh go leith ar chrainn.',
    'Bhí ocht tábla ar fad ar a maraídís na híobairtí.',
    'Sáraíonn sé na seacht nó na hocht bliana.',
    'Tá seacht lampa air agus seacht píopa ar gach ceann díobh.',
    'A aon, a dó, a trí.',
    'Ba é a aon aidhm ar an saol daoine a ghnóthú don chúis.',
    'Tá an Rialtas tar éis áit na Gaeilge i saol na tíre a ceistiú.',
    'Ach sin scéal eile mar a déarfadh an té a déarfadh.',
    'Is iomaí uair a fuair mé locht ar an rialtas.',
    'Bhíodar ag rá ar an aonach gur agamsa a bhí na huain ab fearr.',
    'Ní bheidh ach mhallacht i ndán dó ó na ciníocha agus fuath ó na náisiúin.',
    'Ní theastaíonn uaithi ach bheith ina ball den chumann.',
    'An bhfuil aon uachtar reoite ar an cuntar?',
    'Baintear feidhm as chun aicídí súl a mhaolú.',
    'Má shuíonn tú ag bhord le flaith, tabhair faoi deara go cúramach céard atá leagtha romhat.',
    'Tá sí ag ullmhú é.',
    'Chuir sí ag machnamh é.',
    'Bhí neach oilbhéasach ag leanúint mé.',
    'Bláthaíonn sé amhail bhláth an mhachaire.',
    'An chuir an bhean bheag mórán ceisteanna ort?',
    'An ndeachaigh tú ag iascaireacht inniu?',
    'An raibh aon bhealach praiticiúil eile chun na hIndia?',
    'An dhearna mé an rud ceart?',
    'An bainim sult as bás an drochdhuine?',
    'An éireodh níos fearr leo dá mba mar sin a bheidís?',
    'Ní féidir an Gaeltacht a choinneáil mar réigiún Gaeilge go náisiúnta gan athrú bunúsach.',
    'I gcás An Comhairle Ealaíon ní mór é seo a dhéanamh.',
    'An bean sin, tá sí ina múinteoir.',
    'Chuala sé a mháthair ag labhairt chomh caoin seo leis an mbean nua.',
    'Chinn sé an cruinniú a chur ar an méar fhada.',
    'Cad é an chomhairle a thug an ochtapas dó?',
    'An Acht um Chomhionannas Fostaíochta.',
    'Dath bánbhuí éadrom atá ar an adhmad.',
    'Chóirigh sé na lampaí le solas a chaitheamh os comhair an coinnleora.',
    'Comhlánóidh saoránacht an Aontais an saoránacht náisiúnta agus ní ghabhfaidh sí a hionad.',
    'Ritheann an Sláine tríd an pháirc.',
    'Ní raibh guth an séiléara le clos a thuilleadh.',
    'Tá sin ráite cheana féin acu le muintir an tíre seo.',
    'Is é is dóichí go raibh baint ag an eisimirce leis an laghdú i líon an gcainteoirí Gaeilge.',
    'Is iad an trí cholún le chéile an tAontas Eorpach.',
    'Sheol an ceithre mhíle de na meirligh amach san fhásach.',
    'Ní bhíonn an dhíograis ná an dhúthracht i gceist.',
    'An fhéidir le duine ar bith eile breathnú ar mo script?',
    'Ní bhíonn aon dhá chlár as an chrann chéanna mar a chéile go díreach.',
    'Ní bheidh aon buntáiste againn orthu sin.',
    'Rogha aon de na focail a tháinig i d\'intinn.',
    'Ná hith aon arán gabhála mar aon léi.',
    'Freagair aon dá cheann ar bith díobh seo a leanas.',
    'Bhíomar ag féachaint ar an Ghaeltacht mar ionad chun feabhas a chur ar ar gcuid Gaeilge.',
    'Bhí daoine le fáil i Sasana a chreid gach ar dúradh sa bholscaireacht.',
    'Tá treoirlínte mionsonraithe curtha ar fail ag an gCoimisiún.',
    'Bhí cead againn fanacht ag obair ar an talamh ar fead trí mhí.',
    'Tá sé an chéad suíomh gréasán ar bronnadh teastas air.',
    'Cosc a bheith ar cic a thabhairt don sliotar.',
    'Cosc a bheith ar CIC leabhair a dhíol.',
    'Beidh cairde dá cuid ar Gaeilgeoirí iad.',
    'Ar gcaith tú do chiall agus do chéadfaí ar fad?',
    'Ní amháin ár dhá chosa, ach nigh ár lámha!',
    'Gheobhaimid maoin de gach sórt, agus líonfaimid ár tithe le creach.',
    'Níl aon ní arbh fiú a shantú seachas í.',
    'Ba maith liom fios a thabhairt anois daoibh.',
    'Dúirt daoine go mba ceart an poll a dhúnadh suas ar fad.',
    'Ba eol duit go hiomlán m\'anam.',
    'Tá beinn agus buaic orm.',
    'D\'fhan beirt buachaill sa champa.',
    'D\'fhan beirt bhuachaill cancrach sa champa.',
    'Mothóidh Pobal Osraí an bheirt laoch sin uathu.',
    'Ní amháin bhur dhá chosa, ach nigh bhur lámha!',
    'Déanaigí beart leis de réir bhur briathra.',
    'Cad déarfaidh mé libh mar sin?',
    'Cé mhéid gealladh ar briseadh ar an Indiach bocht?',
    'Nach raibh a fhios aige cé mhéad daoine a bhíonn ag éisteacht leis an stáisiún.',
    'Faigh amach cé mhéad salainn a bhíonn i sampla d\'uisce.',
    'Cá áit a nochtfadh sé é féin ach i mBostún!',
    'Cá chás dúinn bheith ag máinneáil thart anseo?',
    'Cá mhinice ba riachtanach dó stad?',
    'Cá n-oibrigh an t-údar sular imigh sí le ceol?',
    'Cá raibh na rudaí go léir?',
    'Cá cuireann tú do thréad ar féarach?',
    'Cá úsáidfear an mhóin?',
    'Cár fág tú eisean?',
    'Cár bhfág tú eisean?',
    'Cár fágadh eisean?',
    'Sin é a dhéantar i gcas cuntair oibre cistine.',
    'Cé iad na fir seo ag fanacht farat?',
    'Cé ea, rachaidh mé ann leat.',
    'Cé an ceart atá agamsa a thuilleadh fós a lorg ar an rí?',
    'D\'fhoilsigh sí a céad cnuasach filíochta i 1995.',
    'Chuir siad fios orm ceithre uaire ar an tslí sin.',
    'Beidh ar Bhord Feidhmiúcháin an tUachtarán agus ceithre ball eile.',
    'Tá sé tuigthe aige go bhfuil na ceithre dúile ann.',
    'Cén amhránaí is fearr leat?',
    'Cén slí ar fhoghlaim tú an teanga?',
    'Cha dtug mé cur síos ach ar dhá bhabhta collaíochta san úrscéal ar fad.',
    'Bhí an chéad cruinniú den Choimisiún i Ros Muc i nGaeltacht na Gaillimhe.',
    'Tá sé chomh iontach le sneachta dearg.',
    'Chuir mé céad punt chuig an banaltra.',
    'Níl tú do do sheoladh chuig dhaoine a labhraíonn teanga dhothuigthe.',
    'Seo deis iontach chun an Ghaeilge a chur chun chinn.',
    'Tiocfaidh deontas faoin alt seo chun bheith iníoctha.',
    'D\'éirídís ar maidin ar a ceathair a clog.',
    'Shocraigh sé ar an toirt gur choir an t-ábhar tábhachtach seo a phlé leis na daoine.',
    'Caithfidh siad turas cúig uaire a chloig a dhéanamh.',
    'Bhí sé cúig bhanlámh ar fhad, cúig banlámh ar leithead.',
    'Beirim mo mhionn dar an beart a rinne Dia le mo shinsir.',
    'An lá dar gcionn nochtadh gealltanas an Taoisigh sa nuachtán.',
    'Sa dara bliain déag dár braighdeanas, tháinig fear ar a theitheadh.',
    'Beidh picéid ar an monarcha óna naoi a chlog maidin Dhé Luain.',
    'Bíonn ranganna ar siúl oíche Dhéardaoin.',
    'Cuireadh tús le himeachtaí ar Dhéardaoin na Féile le cluiche mór.',
    'D\'oibrigh mé liom go dtí Dé Aoine.',
    'Míle naoi gcéad a hocht ndéag is fiche.',
    'Feicim go bhfuil aon duine déag curtha san uaigh seo.',
    'D\'fhás sé ag deireadh na naoú haoise déag agus fás an náisiúnachais.',
    'Tabharfaidh an tUachtarán a óráid ag leath i ndiaidh a dó déag Dé Sathairn.',
    'Bhuail an clog a trí dhéag.',
    'Tá trí déag litir san fhocal seo.',
    'Tógfaidh mé do coinnleoir óna ionad, mura ndéana tú aithrí.',
    'Is cúis imní don pobal a laghad maoinithe a dhéantar ar Naíscoileanna.',
    'Daoine eile atá ina mbaill den dhream seo.',
    'Creidim go raibh siad de an thuairim seo.',
    'Tá dhá teanga oifigiúla le stádas bunreachtúil á labhairt sa tír seo.',
    'Dhá fiacail lárnacha i ngach aon chomhla.',
    'Rug sí greim ar mo dhá gualainn agus an fhearg a bhí ina súile.',
    'Bhí an dá taobh seo dá phearsantacht le feiceáil go soiléir.',
    'Bhí Eibhlín ar a dhá glúin.',
    'Is léir nach bhfuil an dhá theanga ar chomhchéim lena chéile.',
    'Tionóladh an chéad dhá chomórtas i nGaoth Dobhair.',
    'Cá bhfuil feoil le fáil agamsa le tabhairt do an mhuintir?',
    'Is amhlaidh a bheidh freisin do na tagairtí do airteagail.',
    'Tá sé de chúram seirbhís a chur ar fáil do a chustaiméirí i nGaeilge.',
    'Seinnigí moladh ar an gcruit do ár máthair.',
    'Is é seo mo Mhac muirneach do ar thug mé gnaoi.',
    'Tá an domhan go léir faoi suaimhneas.',
    'Caithfidh pobal na Gaeltachta iad féin cinneadh a dhéanamh faoi an Ghaeilge.',
    'Cuireann sí a neart mar chrios faoi a coim.',
    'Cuireann sé ciníocha faoi ár smacht agus cuireann sé náisiúin faoinár gcosa.',
    'Tá dualgas ar an gComhairle sin tabhairt faoin cúram seo.',
    'Tugadh mioneolas faoin dtionscnamh seo in Eagrán a haon.',
    'Bhí lúcháir ar an Tiarna faoina dhearna sé!',
    'Ní bheidh gearán ag duine ar bith faoin gciste fial atá faoinár cúram.',
    'Beidh paráid Lá Fhéile Phádraig i mBostún.',
    'Tá Féile Bhealtaine an Oireachtais ar siúl an tseachtain seo.',
    'Fágtar na mílte eile gan ghéaga nó radharc na súl.',
    'Tá ar chumas an duine saol iomlán a chaitheamh gan theanga eile á brú air.',
    'Tá gruaim mhór orm gan Chaitlín.',
    'Deir daoine eile, áfach, gur dailtín gan maith é.',
    'Fuarthas an fear marbh ar an trá, a chorp gan máchail gan ghortú.',
    'Dúirt sé liom gan pósadh.',
    'Na duilleoga ar an ngas beag, cruth lansach orthu agus iad gan cos fúthu.',
    'D\'fhág sin gan meas dá laghad ag duine ar bith air.',
    'Tá mé gan cos go brách.',
    'Níl sé ceadaithe aistriú ó rang go chéile gan cead a fháil uaim.',
    'Is stáit ilteangacha iad cuid mhór de na stáit sin atá aonteangach go oifigiúil.',
    'Ní bheidh bonn comparáide ann go beidh torthaí Dhaonáireamh 2007 ar fáil.',
    'Rug sé ar ais mé go dhoras an Teampaill.',
    'Tiocfaidh coimhlintí chun tosaigh sa Chumann ó am go chéile.',
    'Is turas iontach é an turas ó bheith i do thosaitheoir go bheith i do mhúinteoir.',
    'Chuaigh mé suas go an doras cúil a chaisleáin.',
    'Tháinig Pól Ó Coileáin go mo theach ar maidin.',
    'Bhí an teachtaireacht dulta go m\'inchinn.',
    'Tar, téanam go dtí bhean na bhfíseanna.',
    'Agus rachaidh mé siar go dtí thú tráthnóna, más maith leat.',
    'Ba mhaith liom gur bhfágann daoine óga an scoil agus iad ullmhaithe.',
    'Bhraith mé gur fuair mé boladh trom tais uathu.',
    'An ea nach cás leat gur bhfág mo dheirfiúr an freastal fúmsa i m\'aonar?',
    'B\'fhéidir gurbh fearr é seo duit ná leamhnacht na bó ba mhilse i gcontae Chill Mhantáin.',
    'Tá ainm i n-easnamh a mbeadh coinne agat leis.',
    'Tá ainm i easnamh a mbeadh coinne agat leis.',
    'An bhfuil aon uachtar reoite agat i dhá chuisneoir?',
    'An bhfuil aon uachtar reoite agat i cuisneoir?',
    'An bhfuil aon uachtar reoite agat i chuisneoir?',
    'Táimid ag lorg 200 Club Gailf i gach cearn d\'Éirinn.',
    'An bhfuil aon uachtar reoite agaibh i bhur mála?',
    'Bhí slám de pháipéar tais ag cruinniú i mhullach a chéile.',
    'Fuair Derek Bell bás tobann i Phoenix.',
    'Tá níos mó ná 8500 múinteoir ann i thart faoi 540 scoil.',
    'An bhfuil aon uachtar reoite agat i an chuisneoir?',
    'An bhfuil aon uachtar reoite agat i na cuisneoirí?',
    'An bhfuil aon uachtar reoite i a cuisneoir?',
    'Roghnaigh na teangacha i a nochtar na leathanaigh seo.',
    'Rinne gach cine é sin sna cathracha i ar lonnaíodar.',
    'An bhfuil aon uachtar reoite i ár mála?',
    'Thug sé seo deis dom breathnú in mo thimpeall.',
    'Phós sí Pádraig, fear ón mBlascaod Mór, in 1982.',
    'Phós sí Pádraig, fear ón mBlascaod Mór, in 1892.',
    'Theastaigh uaibh beirt bheith in bhur scríbhneoirí.',
    'Beidh an spórt seo á imirt in dhá ionad.',
    'Cad é an rud is mó faoi na Gaeil ina chuireann sé suim?',
    'Tá beirfean inár craiceann faoi mar a bheimis i sorn.',
    'Is tuar dóchais é an méid dul chun cinn atá déanta le bhlianta beaga.',
    'Leanaigí oraibh le bhur ndílseacht dúinn.',
    'Baineann an scéim le thart ar 28,000 miondíoltóir ar fud na tíre.',
    'Níor cuireadh aon tine síos, ar ndóigh, le chomh breá is a bhí an aimsir.',
    'Tá sí ag teacht le thú a fheiceáil.',
    'D\'fhéadfadh tábhacht a bheith ag baint le an gcéad toisc díobh sin.',
    'Molann an Coimisiún go maoineofaí scéim chun tacú le na pobail.',
    'Labhraíodh gach duine an fhírinne le a chomharsa.',
    'Le halt 16 i ndáil le hiarratas ar ordú le a meastar gur tugadh toiliú.',
    'Beir i do láimh ar an tslat le ar bhuail tú an abhainn, agus seo leat.',
    'Ba mhaith liom buíochas a ghlacadh le ár seirbhís riaracháin.',
    'Tógann siad cuid de le iad féin a théamh.',
    'Tá do scrios chomh leathan leis an farraige.',
    'Cuir alt eile lenar bhfuil scríofa agat i gCeist a trí.',
    'Is linne í ar ndóigh agus lenár clann.',
    'Má thiocfaidh acmhainní breise ar fáil, beidh mé sásta.',
    'Má tugann rí breith ar na boicht le cothromas, bunófar a ríchathaoir go brách.',
    'Má deirim libh é, ní chreidfidh sibh.',
    'Má tá suim agat sa turas seo, seol d\'ainm chugamsa.',
    'Má fuair níor fhreagair sé an facs.',
    'Roghnaítear an bhliain 1961 mar pointe tosaigh don anailís.',
    'Aithnítear é mar an údarás.',
    'Más mhian leat tuilleadh eolais a fháil, scríobh chugainn.',
    'Tá caitheamh na hola ag dul i méad i gcónaí.',
    'Tosaíodh ar mhodh adhlactha eile ina mbaintí úsáid as clocha measartha móra.',
    'Comhlíon mo aitheanta agus mairfidh tú beo.',
    'Ceapadh mise i mo bolscaire.',
    'Tá mé ag sclábhaíocht ag iarraidh mo dhá gasúr a chur trí scoil. ',
    'Agus anois bhí mórsheisear iníonacha ag an sagart.',
    'Mura dtuig siad é, nach dóibh féin is mó náire?',
    'Mura bhfuair, sin an chraobh aige.',
    'Mura tagann aon duine i gcabhair orainn, rachaimid anonn chugaibh.',
    'Fiú mura éiríonn liom, beidh mé ábalta cabhrú ar bhonn deonach.',
    'Murach bheith mar sin, bheadh sé dodhéanta dó oibriú na huaireanta fada.',
    'Murar chruthaítear lá agus oíche... teilgim uaim sliocht Iacóib.',
    'Murar gcruthaigh mise lá agus oíche... teilgim uaim sliocht Iacóib.',
    'An bhfuil aon uachtar reoite ag fear na bád?',
    'Is mór ag náisiún na Éireann a choibhneas speisialta le daoine de bhunadh na hÉireann atá ina gcónaí ar an gcoigríoch.',
    'Chuir an Coimisiún féin comhfhreagras chuig na eagraíochtaí seo ag lorg eolais faoina ngníomhaíochtaí.',
    'Tá an tréith sin coitianta i measc na nÉireannaigh sa tír seo.',
    'Athdhéantar na snáithe i ngach ceann de na curaclaim seo.',
    'Ná iompaígí chun na n-íol, agus ná dealbhaígí déithe de mhiotal.',
    'Tá tú níos faide sa tír ná is dleathach duit a bheith.',
    'Ach ní sin an cultúr a bhí ná atá go fóill.',
    'Agus creid nó ná chreid, nach bhfuil an lámhscríbhinn agam féin.',
    'Is fearr de bhéile luibheanna agus grá leo ná mhart méith agus gráin leis.',
    'Is fearr an bás ná bheith beo ar dhéirc.',
    'Nach raibh dóthain eolais aige?',
    'Nach bainfidh mé uaidh an méid a ghoid sé uaim?',
    'Nach ghasta a fuair tú í!',
    'Tháinig na bróga chomh fada siar le haimsir Naomh Phádraig féin.',
    'Nár breá liom claíomh a bheith agam i mo ghlac!',
    'Nár bhfreagair sé thú, focal ar fhocal.',
    'Feicimid gur de dheasca a n-easumhlaíochta nárbh féidir leo dul isteach ann.',
    'Ní fuaireamar puinn eile tuairisce air i ndiaidh sin.',
    'Ní chuireadar aon áthas ar Mhac Dara.',
    'Ní dúirt sé cad a bhí déanta acu.',
    'Ní féadfaidh a gcuid airgid ná óir iad a shábháil.',
    'Ní bhfaighidh tú aon déirce uaim.',
    'Ní deir sé é seo le haon ghráin.',
    'Ní iad sin do phíopaí ar an tábla!',
    'Ní dheireadh aon duine acu aon rud liom.',
    'Ní fhéidir dóibh duine a shaoradh ón mbás.',
    'Tá tuairisc ar an léacht a thug Niamh Nic Suibhne ar leathanach a hocht.',
    'Is saoririseoir agus ceoltóir í Aoife Nic Chormaic.',
    '"Tá," ar sise, "ach níor fhacthas é sin."',
    'Níor gá do dheoraí riamh codladh sa tsráid; Bhí mo dhoras riamh ar leathadh.',
    '"Tá," ar sise, "ach níor fuair muid aon ocras fós.',
    'Níor mbain sé leis an dream a bhí i gcogar ceilge.',
    'Níorbh foláir dó éisteacht a thabhairt dom.',
    'Eoghan Ó Anluain a thabharfaidh léacht deiridh na comhdhála.',
    'Ach anois ó cuimhním air, bhí ardán coincréite sa pháirc.',
    'Bhuel, fan ar strae mar sin ó tá tú chomh mímhúinte sin.',
    'Ní maith liom é ar chor ar bith ó fuair sé an litir sin.',
    'Tabhair an t-ordú seo leanas ó béal.',
    'Bíodh bhur ngrá saor ó an chur i gcéill.',
    'Beidh an chéad chruinniú oifigiúil ag an gcoiste oíche Dé Luain.',
    'Bíodh bhur ngrá saor ón cur i gcéill.',
    'Ná glacaim sos ón thochailt.',
    'Amharcann sé ó a ionad cónaithe ar gach aon neach dá maireann ar talamh.',
    'Seo iad a gcéimeanna de réir na n-áiteanna ó ar thosaíodar.',
    'Agus rinne sé ár bhfuascailt ó ár naimhde.',
    'Seo teaghlach ag a bhfuil go leor fadhbanna agus ónar dteastaíonn tacaíocht atá dírithe.',
    'Bhíodh súil in airde againn ónár túir faire.',
    'Tá do ghéaga spréite ar bhraillín ghléigeal os fharraige faoileán.',
    'Ar ais leis ansin os chomhair an teilifíseáin.',
    'Uaidh féin, b\'fhéidir, pé é féin.',
    'Agus tháinig scéin air roimh an pobal seo ar a líonmhaireacht.',
    'Is gaiste é eagla roimh daoine.',
    'An bhfuil aon uachtar reoite agat sa oighear?',
    'Gortaíodh ceathrar sa n-eachtra.',
    'An bhfuil aon uachtar reoite agat sa cuisneoir?',
    'Ní mór dom umhlú agus cic maith sa thóin a thabhairt duit. ',
    'An bhfuil aon uachtar reoite agat sa seamair?',
    'An bhfuil aon uachtar reoite agat sa scoil?',
    'An bhfuil aon uachtar reoite agat sa samhradh?',
    'Tá sé bráthair de chuid Ord San Phroinsias.',
    'San fásach cuirfidh mé crainn chéadrais.',
    'An bhfuil aon uachtar reoite agat san foraois?',
    'Tugaimid faoi abhainn na Sionainne san bhád locha ó Ros Comáin.',
    'Tógadh an foirgneamh féin san 18ú haois.',
    'Ní féidir iad a sheinm le snáthaid ach cúig nó sé uaire.',
    'Dúirt sé uair amháin nach raibh áit eile ar mhaith leis cónaí ann.',
    'Céard atá ann ná sé cathaoirleach coiste.',
    'Cuireadh boscaí ticeála isteach seachas bhoscaí le freagraí a scríobh isteach.',
    'Dá ndéanfadh sí amhlaidh réiteodh sí an fhadhb seachas bheith á ghéarú.',
    'Is siad na rudaí crua a mhairfidh.',
    'Tá ar a laghad ceithre ní sa litir a chuir scaoll sna oifigigh.',
    'Soláthraíonn an Roinn seisiúin sna Gaeilge labhartha do na mic léinn.',
    'Sula sroicheadar an bun arís, bhí an oíche ann agus chuadar ar strae.',
    'Sula ndearna sé amhlaidh, más ea, léirigh sé a chreidiúint san fhoireann.',
    'Iompróidh siad thú lena lámha sula bhuailfeá do chos in aghaidh cloiche.',
    'Ach sular sroich sé, dúirt sí: "Dúnaigí an doras air!"',
    'Chuir sé iad ina suí mar a raibh onóir acu thar an cuid eile a fuair cuireadh.',
    'Bhí an chathair ag cur thar maol le filí de gach cineál.',
    'Timpeall trí uaire a chloig ina dhiaidh sin tháinig an bhean isteach.',
    'Scríobhaim chugaibh mar gur maitheadh daoibh bhur bpeacaí trí a ainm.',
    'Cuirtear i láthair na struchtúir trí a reáchtálfar gníomhartha ag an leibhéal náisiúnta.',
    'Ní fhillfidh siad ar an ngeata trí ar ghabh siad isteach.',
    'Beirimid an bua go caithréimeach trí an té úd a thug grá dúinn.',
    'Coinníodh lenár sála sa chaoi nárbh fhéidir siúl trí ár sráideanna.',
    'Gabhfaidh siad trí muir na hÉigipte.',
    'Feidhmeoidh an ciste coimisiúnaithe tríd na foilsitheoirí go príomha.',
    'Ba é an gleann cúng trína ghabh an abhainn.',
    'Is mar a chéile an próiseas trínar ndéantar é seo.',
    'Mar trínár peacaí, tá do phobal ina ábhar gáire ag cách máguaird orainn.',
    'Beidh cúrsa Gaeilge ar siúl do mhic léinn in Áras Mháirtín Uí Cadhain.',
    'Nár thug sí póg do gach uile duine?',
    'D\'ith na daoine uile bia.',
    'Idir dhá sholas, um tráthnóna, faoi choim na hoíche agus sa dorchadas.',
    'Straitéis Chomhphobail um bainistíocht dramhaíola.',
    'Bhíodh an dinnéar acu um mheán lae.',
    'Conas a bheadh Éirinn agus Meiriceá difriúil?',
    'Ba chois tine é.',
    'Bhí cuid mhór teannais agus iomaíochta ann.',
    'Galar crúibe is béil.',
    'Caitheann sé go leor ama ann.',
    'An raibh mórán daoine ag an tsiopa?',
    'Ní raibh dúil bheo le feiceáil ar na bhfuinneog.',
    'Bhí, dála an scéil, ocht mbean déag aige.',
    'Cá bhfuil an tseomra?',
    'Is iad na nGardaí.',
    'Éirí Amach na Cásca.',
    'Leas phobal na hÉireann agus na hEorpa.',
    'Fáilte an deamhain is an diabhail romhat.',
    'Go deo na ndeor, go deo na díleann.',
    'Clann na bPoblachta a thug siad orthu féin.',
    'Cruthaíodh an chloch sin go domhain faoin dtalamh.',
    'Tá ainm in n-easnamh a mbeadh coinne agat leis.',
    'Tá muid compordach inar gcuid "fírinní" féin.',
    'Tá siad ag éileamh go n-íocfaí iad as a gcuid costais agus iad mbun traenála.',
    'Cruthaíodh an chloch sin go domhain faoin gcrann.',
    'An n-ólfaidh tú rud éigin?',
    'Nach holc an mhaise duit a bheith ag magadh.',
    'Dún do bhéal, a mhiúil na haon chloiche!',
    'Scaoileadh seachtar duine chun báis i mBaile Átha Cliath le hocht mí anuas.',
    'Ní dhúnfaidh an t-ollmhargadh go dtí a haon a chlog ar maidin.',
    'Is mar gheall ar sin atá líníocht phictiúrtha chomh húsáideach sin.',
    'Tá sí ag feidhmiú go héifeachtach.',
    'Ní hionann cuingir na ngabhar agus cuingir na lánúine.',
    'Ba hiad na hamhráin i dtosach ba chúis leis.',
    'Ní hé lá na gaoithe lá na scolb.',
    'Ba iad na trí háit iad Bostún, Baile Átha Cliath agus Nua Eabhrac.',
    'Phós sé bean eile ina háit.',
    'Cá ham a tháinig sí a staidéar anseo ó thús?',
    'Bhí a dheartháir ag siúl na gceithre hairde agus bhí seisean ina shuí.',
    'Chaith sé an dara hoíche i Sligeach.',
    'Tá sé i gcóip a rinneadh i lár na cúigiú haoise déag.',
    'Chuir sí a dhá huillinn ar an bhord.',
    'Chuir mé mo dhá huillinn ar an bhord.',
    'Cuireadh cuid mhaith acu go hÉirinn.',
    'Tá tús curtha le clár chun rampaí luchtaithe a chur sna hotharcharranna.',
    'Cuimhnígí ar na héachtaí a rinne sé.',
    'Creidim go mbeidh iontas ar mhuintir na hÉireann nuair a fheiceann siad an feidhmchlár seo.',
    'Tháinig múinteoir úr i gceithre huaire fichead.',
    'Caithfidh siad turas cúig huaire a chloig a dhéanamh.',
    'In Éirinn chaitheann breis is 30 faoin gcéad de mhná toitíní.',
    'Chuirfear in iúl do dhaoine gurb é sin an aidhm atá againn.',
    'Déan cur síos ar dhá thoradh a bhíonn ag caitheamh tobac ar an tsláinte.',
    'Má bhrúitear idir chnónna agus bhlaoscanna faightear ola inchaite.',
    'Ní chothaíonn na briathra na bráithre.',
    'Cha bhíonn striapachas agus seafóid Mheiriceá ann feasta.',
    'Tá cleachtadh ag daoine ó bhíonn siad an-óg ar uaigneas imeachta.',
    'Ar an láithreán seo gheofar foclóirí agus liostaí téarmaíochta.',
    'An oíche sin, sular chuaigh sé a chodladh, chuir sé litir fhada dom.',
    'Tá mioneolas faoinar rinne sé ansin.',
    'Níor rinneadh a leithéid le fada agus ní raibh aon slat tomhais acu.',
    'Teastaíonn uaidh an scéal a insint sula ngeobhaidh sé bás.',
    'Tá folúntas sa chomhlacht ina tá mé ag obair faoi láthair.',
    'Ní gheobhaidh an mealltóir nathrach aon táille.',
    'Má dhearna sí praiseach de, thosaigh sí arís go bhfuair sí ceart é.',
    'Nuair a raibh mé óg.',
    'An clapsholas a raibh mé ag dréim leis.',
    'Chan fhacthas dom go raibh an saibhreas céanna i mBéarla.',
    'Chuaigh sé chun na huaimhe agus fhéach sé isteach.',
    'Fágadh faoi smacht a lámh iad.',
    'An íosfá ubh eile?',
    'Níorbh fhada, ámh, gur d\'fhoghlaim sí an téarma ceart uathu.',
    'Nílim ag rá gur d\'aon ghuth a ainmníodh Sheehy.',
    'Scríobh sé soiscéal ina d\'athródh an eaglais í féin go deo.',
    'Tá bonn i bhfad níos dhoimhne ná sin le Féilte an Oireachtais.',
    'Tá a chuid leabhar tiontaithe go dhá theanga fichead.',
    'Tá dún cosanta eile ar an taobh thoir den oileán.',
    'Déan teagmháil leis an Rannóg ag an seoladh thuasluaite.',
    'Nochtadh na fírinne sa dóigh a n-admhódh an té is bréagaí í.',
    'Abairt a chuireann in iúl dearóile na hÉireann sa 18ú agus sa 19ú haois.',
    'Oíche na gaoithe móra.',
    'Oíche na gaoithe mór.',
    'Tá a chumas sa Ghaeilge níos airde ná cumas na bhfear óga.',
    'Beirt bhan Mheiriceánacha a bhí ann.',
    'Tá sé-- tá sé- mo ---shin-seanathair.',
    'Is foláir dóibh a ndualgais a chomhlíonadh.',
    'Bhain na toibreacha le re eile agus le dream daoine atá imithe.',
    'Labhair mé ar shon na daoine.',
    'Tá sé tábhachtach bheith ag obair an son na cearta.',
    'Ba é an fear an phortaigh a tháinig thart leis na plátaí bia.',
    'Tá dhá shiombail ag an bharr gach leathanaigh.',
    'Tabharfaimid an t-ainm do mháthar uirthi.',
    'Is iad na trí cheist sin.',
    'Lena chois sin, dá bharr seo, dá bhrí sin, ina aghaidh seo.',
    'Cén t-ionadh sin?',
    'Ba é an fear an phortaigh a tháinig thart leis na plátaí bia.',
    'Tá dhá shiombail ag an bharr gach leathanaigh.',
    'Tabharfaimid an t-ainm do mháthar uirthi.',
    'This is a test sentence.',
    'Visit my website for more information.',
    'I have 10 apples and 5 oranges.',
    'I like to eat apples and oranges.',
    'Éireann go brách!'
];
