export const COUNTY_NAMES = {
    "Dublin": "Contae Átha Cliath",
    "Monaghan": "Contae Mhuineacháin",
    "Galway": "Contae na Gaillimhe",
    "Cork": "Contae Chorcaí­",
    "Limerick": "Contae Luimnigh",
    "Waterford": "Contae Phort Láirge",
    "Tipperary": "Contae Thiobraid Árann",
    "Louth": "Contae Lú",
    "Mayo": "Contae Mhaigh Eo",
    "Meath": "Contae na Mí",
    "Offaly": "Contae Uí­bh Fhailí",
    "Westmeath": "Contae na hIarmhí­",
    "Wexford": "Contae Loch Garman",
    "Wicklow": "Contae Chill Mhantáin",
    "Kildare": "Contae Chill Dara",
    "Kilkenny": "Contae Chill Chainnigh",
    "Laois": "Contae Laoise",
    "Kerry": "Contae Chiarraí",
    "Roscommon": "Contae Ros Comáin",
    "Sligo": "Contae Shligigh",
    "Donegal": "Contae Dhún na nGall",
    "Leitrim": "Contae Liatroma",
    "Longford": "Contae an Longfoirt",
    "Clare": "Contae an Chláir",
    "Carlow": "Contae Cheatharlach",
    "Cavan": "Contae an Chabháin",
    "Belfast": "Béal Feirste",
    "Antrim": "Contae Aontroma",
    "Armagh": "Contae Ard Mhacha",
    "Derry": "Contae Dhoire",
    "Down": "Contae an Dúin",
    "Tryone": "Contae Thír Eoghain",
    "Fermanagh": "Contae Fhear Manach"
  } as const;